name: Deploy to Render Demo

# on:
#     workflow_run:
#         workflows: ['Build and Publish Docker Images Demo']
#         branches: [develop, temp]
#         types:
#             - completed
on:
  push:
    branches:
      - develop
jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    environment: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Render CLI
        run: |
          wget  -O render https://github.com/render-oss/render-cli/releases/download/v0.1.8/render-linux-x86_64
          chmod +x render
          sudo mv render /usr/local/bin/render
          mkdir ~/.render
          cat << EOF > ~/.render/config.yaml
                version: 1
                sshPreserveHosts: true
                profiles:
                  default:
                    defaultRegion: oregon
                    apiKey: rnd_lrPwozNQ9dL1SbnM2KqKS2kpFNRt
                  test:
                    defaultRegion: oregon
                    apiKey: rnd_lrPwozNQ9dL1SbnM2KqKS2kpFNRt
                EOF
      - name: Deploy Services
        run: |
          render blueprint from-template --profile test
        env:
          RENDER_EMAIL: "rohit997166.prasad@gmail.com"
          RENDER_PASSWORD: "Rohit123@"
