name: Deploy to Render Demo

# on:
#     workflow_run:
#         workflows: ['Build and Publish Docker Images Demo']
#         branches: [develop, temp]
#         types:
#             - completed
on:
  push:
    branches:
      - develop
jobs:
    deploy-demo:
        runs-on: ubuntu-latest

        environment: demo

        steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Render CLI
           run: |
             curl -o render https://render.com/static/render-cli-linux
             chmod +x render
             sudo mv render /usr/local/bin/render
           env:
             RENDER_EMAIL: "rohit997166.prasad@gmail.com"
             RENDER_PASSWORD: "Rohit123@"

         - name: Deploy Services
           run: |
                 render service push
           env:
             RENDER_EMAIL: "rohit997166.prasad@gmail.com"
             RENDER_PASSWORD: "Rohit123@"
